#server
server:
  port: 8080
#feign log
logging:
  level:
    com:
      happyzombie:
        springinitializr:
          feignclient:
    .*: info
#quartz
spring:
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
